[package]
name = "smudge-timer"
version = "0.1.12"
edition = "2024"

[dependencies]
gtk4 = "0.10.3"
rdev = "0.5"

[target.'cfg(windows)'.dependencies]
gdk4-win32 = "0.10.3"
gdk4-win32-sys = "0.10.3"
glib = "0.21.5"
